# Generated by Django 6.0.3 on 2026-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_customgoal_customgoalcheckin_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_photos/'),
        ),
        migrations.AddField(
            model_name='customgoalcheckin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_photos/'),
        ),
    ]
